/*
# CampusSphere Schema Part 3 — Auto-profile trigger + seed roadmaps

1. Changes
- Create a `handle_new_user` trigger function that inserts a row into `profiles` whenever a new auth.users row is created, using the email and default role 'student'.
- Attach the trigger to `auth.users` after insert.
2. Seed Data
- Insert predefined career roadmaps for 12 careers (full_stack, frontend, backend, java, python, data_analyst, data_scientist, ai_ml, devops, cloud, cybersecurity, software_engineer).
- Each roadmap has phases with tasks including title, description, skill, priority, duration, difficulty.
3. Security
- The trigger function is SECURITY DEFINER so it can insert into profiles even though the caller is the new user.
*/

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
SECURITY DEFINER
SET search_path = public
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (NEW.id, NEW.email, COALESCE(NEW.raw_user_meta_data->>'full_name', ''));
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Seed career roadmaps
INSERT INTO career_roadmaps (career_key, career_name, description, phases) VALUES
('full_stack', 'Full Stack Developer', 'Complete web development from frontend to backend to deployment.', '[
  {"phase":1,"title":"Foundation","tasks":[{"id":"fs1","title":"HTML","description":"Semantic markup and structure","skill":"HTML","priority":"high","duration":"3 days","difficulty":"easy"},{"id":"fs2","title":"CSS","description":"Styling, flexbox, grid","skill":"CSS","priority":"high","duration":"5 days","difficulty":"easy"},{"id":"fs3","title":"JavaScript","description":"ES6+, DOM, async","skill":"JavaScript","priority":"high","duration":"10 days","difficulty":"medium"}]},
  {"phase":2,"title":"Frontend Framework","tasks":[{"id":"fs4","title":"React","description":"Components, hooks, state","skill":"React","priority":"high","duration":"10 days","difficulty":"medium"},{"id":"fs5","title":"TypeScript","description":"Types and interfaces","skill":"TypeScript","priority":"medium","duration":"5 days","difficulty":"medium"},{"id":"fs6","title":"Git","description":"Version control workflow","skill":"Git","priority":"medium","duration":"3 days","difficulty":"easy"}]},
  {"phase":3,"title":"Backend","tasks":[{"id":"fs7","title":"Node.js","description":"Runtime and modules","skill":"Node.js","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"fs8","title":"Express.js","description":"REST API building","skill":"Express","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"fs9","title":"REST APIs","description":"Design and conventions","skill":"APIs","priority":"high","duration":"5 days","difficulty":"medium"}]},
  {"phase":4,"title":"Database","tasks":[{"id":"fs10","title":"MongoDB","description":"NoSQL modeling","skill":"MongoDB","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"fs11","title":"Authentication","description":"JWT and sessions","skill":"Auth","priority":"high","duration":"5 days","difficulty":"medium"},{"id":"fs12","title":"Socket.io","description":"Real-time communication","skill":"WebSocket","priority":"medium","duration":"5 days","difficulty":"medium"}]},
  {"phase":5,"title":"DevOps","tasks":[{"id":"fs13","title":"Docker","description":"Containerization","skill":"Docker","priority":"medium","duration":"5 days","difficulty":"medium"},{"id":"fs14","title":"Deployment","description":"CI/CD pipelines","skill":"DevOps","priority":"medium","duration":"5 days","difficulty":"medium"},{"id":"fs15","title":"Cloud Basics","description":"AWS/GCP fundamentals","skill":"Cloud","priority":"low","duration":"7 days","difficulty":"hard"}]},
  {"phase":6,"title":"Interview Prep","tasks":[{"id":"fs16","title":"Portfolio","description":"Showcase projects","skill":"Portfolio","priority":"high","duration":"5 days","difficulty":"medium"},{"id":"fs17","title":"DSA","description":"Data structures and algorithms","skill":"DSA","priority":"high","duration":"15 days","difficulty":"hard"},{"id":"fs18","title":"System Design","description":"Scalability basics","skill":"System Design","priority":"medium","duration":"7 days","difficulty":"hard"}]}
]'),
('frontend', 'Frontend Developer', 'Build modern, responsive user interfaces.', '[
  {"phase":1,"title":"Foundation","tasks":[{"id":"fe1","title":"HTML","description":"Semantic markup","skill":"HTML","priority":"high","duration":"3 days","difficulty":"easy"},{"id":"fe2","title":"CSS","description":"Flexbox, grid, animations","skill":"CSS","priority":"high","duration":"7 days","difficulty":"easy"},{"id":"fe3","title":"JavaScript","description":"ES6+, DOM manipulation","skill":"JavaScript","priority":"high","duration":"10 days","difficulty":"medium"}]},
  {"phase":2,"title":"Framework","tasks":[{"id":"fe4","title":"React","description":"Components and hooks","skill":"React","priority":"high","duration":"10 days","difficulty":"medium"},{"id":"fe5","title":"TypeScript","description":"Type safety","skill":"TypeScript","priority":"high","duration":"5 days","difficulty":"medium"},{"id":"fe6","title":"Tailwind CSS","description":"Utility-first styling","skill":"Tailwind","priority":"medium","duration":"3 days","difficulty":"easy"}]},
  {"phase":3,"title":"Advanced","tasks":[{"id":"fe7","title":"State Management","description":"Zustand/Redux","skill":"State","priority":"high","duration":"5 days","difficulty":"medium"},{"id":"fe8","title":"Testing","description":"Jest, RTL","skill":"Testing","priority":"medium","duration":"5 days","difficulty":"medium"},{"id":"fe9","title":"Performance","description":"Optimization techniques","skill":"Performance","priority":"medium","duration":"5 days","difficulty":"hard"}]},
  {"phase":4,"title":"Interview Prep","tasks":[{"id":"fe10","title":"Portfolio","description":"Showcase projects","skill":"Portfolio","priority":"high","duration":"5 days","difficulty":"medium"},{"id":"fe11","title":"DSA","description":"Problem solving","skill":"DSA","priority":"high","duration":"15 days","difficulty":"hard"}]}
]'),
('backend', 'Backend Developer', 'Server-side development and APIs.', '[
  {"phase":1,"title":"Foundation","tasks":[{"id":"be1","title":"JavaScript","description":"ES6+ fundamentals","skill":"JavaScript","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"be2","title":"Node.js","description":"Runtime and modules","skill":"Node.js","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"be3","title":"Databases","description":"SQL and NoSQL","skill":"Database","priority":"high","duration":"10 days","difficulty":"medium"}]},
  {"phase":2,"title":"APIs","tasks":[{"id":"be4","title":"Express.js","description":"REST APIs","skill":"Express","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"be5","title":"Authentication","description":"JWT, OAuth","skill":"Auth","priority":"high","duration":"5 days","difficulty":"medium"},{"id":"be6","title":"API Design","description":"Best practices","skill":"APIs","priority":"medium","duration":"5 days","difficulty":"medium"}]},
  {"phase":3,"title":"Advanced","tasks":[{"id":"be7","title":"Microservices","description":"Architecture","skill":"Architecture","priority":"medium","duration":"7 days","difficulty":"hard"},{"id":"be8","title":"Caching","description":"Redis","skill":"Redis","priority":"medium","duration":"5 days","difficulty":"medium"},{"id":"be9","title":"Message Queues","description":"RabbitMQ/Kafka","skill":"Queues","priority":"low","duration":"5 days","difficulty":"hard"}]},
  {"phase":4,"title":"Interview Prep","tasks":[{"id":"be10","title":"DSA","description":"Problem solving","skill":"DSA","priority":"high","duration":"15 days","difficulty":"hard"},{"id":"be11","title":"System Design","description":"Scalability","skill":"System Design","priority":"high","duration":"10 days","difficulty":"hard"}]}
]'),
('java', 'Java Developer', 'Enterprise Java development.', '[
  {"phase":1,"title":"Core Java","tasks":[{"id":"jv1","title":"Java Syntax","description":"Basics and OOP","skill":"Java","priority":"high","duration":"10 days","difficulty":"medium"},{"id":"jv2","title":"Collections","description":"Data structures","skill":"Collections","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"jv3","title":"Concurrency","description":"Multithreading","skill":"Concurrency","priority":"medium","duration":"7 days","difficulty":"hard"}]},
  {"phase":2,"title":"Enterprise","tasks":[{"id":"jv4","title":"Spring Boot","description":"Framework basics","skill":"Spring","priority":"high","duration":"10 days","difficulty":"medium"},{"id":"jv5","title":"REST APIs","description":"Spring MVC","skill":"APIs","priority":"high","duration":"5 days","difficulty":"medium"},{"id":"jv6","title":"JPA/Hibernate","description":"ORM","skill":"Hibernate","priority":"high","duration":"7 days","difficulty":"medium"}]},
  {"phase":3,"title":"Advanced","tasks":[{"id":"jv7","title":"Microservices","description":"Spring Cloud","skill":"Microservices","priority":"medium","duration":"10 days","difficulty":"hard"},{"id":"jv8","title":"Testing","description":"JUnit, Mockito","skill":"Testing","priority":"medium","duration":"5 days","difficulty":"medium"}]},
  {"phase":4,"title":"Interview Prep","tasks":[{"id":"jv9","title":"DSA","description":"Problem solving","skill":"DSA","priority":"high","duration":"15 days","difficulty":"hard"},{"id":"jv10","title":"System Design","description":"Scalability","skill":"System Design","priority":"high","duration":"10 days","difficulty":"hard"}]}
]'),
('python', 'Python Developer', 'Python application development.', '[
  {"phase":1,"title":"Foundation","tasks":[{"id":"py1","title":"Python Basics","description":"Syntax and data types","skill":"Python","priority":"high","duration":"7 days","difficulty":"easy"},{"id":"py2","title":"OOP","description":"Classes and objects","skill":"OOP","priority":"high","duration":"5 days","difficulty":"medium"},{"id":"py3","title":"Data Structures","description":"Lists, dicts, sets","skill":"Data Structures","priority":"high","duration":"5 days","difficulty":"medium"}]},
  {"phase":2,"title":"Web","tasks":[{"id":"py4","title":"Django","description":"Full-stack framework","skill":"Django","priority":"high","duration":"10 days","difficulty":"medium"},{"id":"py5","title":"Flask","description":"Micro framework","skill":"Flask","priority":"medium","duration":"5 days","difficulty":"medium"},{"id":"py6","title":"REST APIs","description":"DRF","skill":"APIs","priority":"high","duration":"5 days","difficulty":"medium"}]},
  {"phase":3,"title":"Advanced","tasks":[{"id":"py7","title":"Testing","description":"pytest","skill":"Testing","priority":"medium","duration":"5 days","difficulty":"medium"},{"id":"py8","title":"Async","description":"asyncio","skill":"Async","priority":"low","duration":"5 days","difficulty":"hard"}]},
  {"phase":4,"title":"Interview Prep","tasks":[{"id":"py9","title":"DSA","description":"Problem solving","skill":"DSA","priority":"high","duration":"15 days","difficulty":"hard"}]}
]'),
('data_analyst', 'Data Analyst', 'Analyze data and build dashboards.', '[
  {"phase":1,"title":"Foundation","tasks":[{"id":"da1","title":"Python","description":"Basics for data","skill":"Python","priority":"high","duration":"7 days","difficulty":"easy"},{"id":"da2","title":"Statistics","description":"Descriptive stats","skill":"Statistics","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"da3","title":"Excel","description":"Advanced functions","skill":"Excel","priority":"medium","duration":"5 days","difficulty":"easy"}]},
  {"phase":2,"title":"Data Tools","tasks":[{"id":"da4","title":"Pandas","description":"Data manipulation","skill":"Pandas","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"da5","title":"NumPy","description":"Numerical computing","skill":"NumPy","priority":"high","duration":"5 days","difficulty":"medium"},{"id":"da6","title":"SQL","description":"Querying databases","skill":"SQL","priority":"high","duration":"7 days","difficulty":"medium"}]},
  {"phase":3,"title":"Visualization","tasks":[{"id":"da7","title":"Matplotlib","description":"Plotting","skill":"Matplotlib","priority":"medium","duration":"5 days","difficulty":"medium"},{"id":"da8","title":"Tableau/Power BI","description":"Dashboards","skill":"BI Tools","priority":"high","duration":"7 days","difficulty":"medium"}]},
  {"phase":4,"title":"Projects","tasks":[{"id":"da9","title":"Data Project","description":"End-to-end analysis","skill":"Projects","priority":"high","duration":"10 days","difficulty":"medium"}]}
]'),
('data_scientist', 'Data Scientist', 'ML and advanced analytics.', '[
  {"phase":1,"title":"Foundation","tasks":[{"id":"ds1","title":"Python","description":"Programming","skill":"Python","priority":"high","duration":"7 days","difficulty":"easy"},{"id":"ds2","title":"Statistics","description":"Probability and inference","skill":"Statistics","priority":"high","duration":"10 days","difficulty":"medium"},{"id":"ds3","title":"Linear Algebra","description":"Vectors and matrices","skill":"Math","priority":"medium","duration":"7 days","difficulty":"medium"}]},
  {"phase":2,"title":"Data","tasks":[{"id":"ds4","title":"Pandas","description":"Data wrangling","skill":"Pandas","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"ds5","title":"SQL","description":"Database queries","skill":"SQL","priority":"high","duration":"7 days","difficulty":"medium"}]},
  {"phase":3,"title":"Machine Learning","tasks":[{"id":"ds6","title":"Scikit-learn","description":"Classical ML","skill":"ML","priority":"high","duration":"10 days","difficulty":"hard"},{"id":"ds7","title":"Model Evaluation","description":"Metrics and validation","skill":"ML","priority":"high","duration":"5 days","difficulty":"medium"}]},
  {"phase":4,"title":"Advanced","tasks":[{"id":"ds8","title":"Deep Learning","description":"Neural networks","skill":"Deep Learning","priority":"medium","duration":"10 days","difficulty":"hard"},{"id":"ds9","title":"NLP","description":"Text processing","skill":"NLP","priority":"low","duration":"7 days","difficulty":"hard"}]}
]'),
('ai_ml', 'AI/ML Engineer', 'Build and deploy ML systems.', '[
  {"phase":1,"title":"Foundation","tasks":[{"id":"ml1","title":"Python","description":"Programming","skill":"Python","priority":"high","duration":"7 days","difficulty":"easy"},{"id":"ml2","title":"Math","description":"Linear algebra, calculus, probability","skill":"Math","priority":"high","duration":"10 days","difficulty":"hard"},{"id":"ml3","title":"Statistics","description":"Inference","skill":"Statistics","priority":"high","duration":"7 days","difficulty":"medium"}]},
  {"phase":2,"title":"ML","tasks":[{"id":"ml4","title":"Scikit-learn","description":"Classical ML","skill":"ML","priority":"high","duration":"10 days","difficulty":"hard"},{"id":"ml5","title":"Feature Engineering","description":"Data prep","skill":"ML","priority":"high","duration":"5 days","difficulty":"medium"}]},
  {"phase":3,"title":"Deep Learning","tasks":[{"id":"ml6","title":"TensorFlow/PyTorch","description":"Frameworks","skill":"DL","priority":"high","duration":"10 days","difficulty":"hard"},{"id":"ml7","title":"CNNs","description":"Computer vision","skill":"CV","priority":"medium","duration":"7 days","difficulty":"hard"},{"id":"ml8","title":"Transformers","description":"Attention models","skill":"NLP","priority":"medium","duration":"7 days","difficulty":"hard"}]},
  {"phase":4,"title":"MLOps","tasks":[{"id":"ml9","title":"Model Deployment","description":"Serving models","skill":"MLOps","priority":"high","duration":"7 days","difficulty":"hard"},{"id":"ml10","title":"ML Pipelines","description":"Automation","skill":"MLOps","priority":"medium","duration":"5 days","difficulty":"hard"}]}
]'),
('devops', 'DevOps Engineer', 'Automation and infrastructure.', '[
  {"phase":1,"title":"Foundation","tasks":[{"id":"do1","title":"Linux","description":"Command line and scripting","skill":"Linux","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"do2","title":"Networking","description":"TCP/IP basics","skill":"Networking","priority":"medium","duration":"5 days","difficulty":"medium"},{"id":"do3","title":"Git","description":"Version control","skill":"Git","priority":"high","duration":"3 days","difficulty":"easy"}]},
  {"phase":2,"title":"Containers","tasks":[{"id":"do4","title":"Docker","description":"Containerization","skill":"Docker","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"do5","title":"Kubernetes","description":"Orchestration","skill":"K8s","priority":"high","duration":"10 days","difficulty":"hard"}]},
  {"phase":3,"title":"CI/CD","tasks":[{"id":"do6","title":"Jenkins/GitHub Actions","description":"Pipelines","skill":"CI/CD","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"do7","title":"Infrastructure as Code","description":"Terraform","skill":"IaC","priority":"medium","duration":"7 days","difficulty":"hard"}]},
  {"phase":4,"title":"Cloud","tasks":[{"id":"do8","title":"AWS","description":"Core services","skill":"AWS","priority":"high","duration":"10 days","difficulty":"hard"},{"id":"do9","title":"Monitoring","description":"Prometheus, Grafana","skill":"Monitoring","priority":"medium","duration":"5 days","difficulty":"medium"}]}
]'),
('cloud', 'Cloud Engineer', 'Cloud infrastructure and services.', '[
  {"phase":1,"title":"Foundation","tasks":[{"id":"cl1","title":"Networking","description":"Fundamentals","skill":"Networking","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"cl2","title":"Linux","description":"Administration","skill":"Linux","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"cl3","title":"Security","description":"Basics","skill":"Security","priority":"medium","duration":"5 days","difficulty":"medium"}]},
  {"phase":2,"title":"AWS","tasks":[{"id":"cl4","title":"EC2","description":"Compute","skill":"AWS","priority":"high","duration":"5 days","difficulty":"medium"},{"id":"cl5","title":"S3","description":"Storage","skill":"AWS","priority":"high","duration":"3 days","difficulty":"easy"},{"id":"cl6","title":"RDS","description":"Databases","skill":"AWS","priority":"high","duration":"5 days","difficulty":"medium"}]},
  {"phase":3,"title":"Advanced","tasks":[{"id":"cl7","title":"IAM","description":"Access management","skill":"AWS","priority":"high","duration":"5 days","difficulty":"medium"},{"id":"cl8","title":"VPC","description":"Networking","skill":"AWS","priority":"medium","duration":"5 days","difficulty":"hard"},{"id":"cl9","title":"Lambda","description":"Serverless","skill":"AWS","priority":"medium","duration":"5 days","difficulty":"hard"}]},
  {"phase":4,"title":"Multi-Cloud","tasks":[{"id":"cl10","title":"Azure","description":"Basics","skill":"Azure","priority":"low","duration":"7 days","difficulty":"hard"},{"id":"cl11","title":"GCP","description":"Basics","skill":"GCP","priority":"low","duration":"7 days","difficulty":"hard"}]}
]'),
('cybersecurity', 'Cybersecurity Engineer', 'Security operations and defense.', '[
  {"phase":1,"title":"Foundation","tasks":[{"id":"cs1","title":"Networking","description":"TCP/IP, OSI","skill":"Networking","priority":"high","duration":"10 days","difficulty":"medium"},{"id":"cs2","title":"Linux","description":"Administration","skill":"Linux","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"cs3","title":"Security Basics","description":"CIA triad","skill":"Security","priority":"high","duration":"5 days","difficulty":"easy"}]},
  {"phase":2,"title":"Offensive","tasks":[{"id":"cs4","title":"Penetration Testing","description":"Methodology","skill":"Pentest","priority":"high","duration":"10 days","difficulty":"hard"},{"id":"cs5","title":"Web Security","description":"OWASP Top 10","skill":"Web Security","priority":"high","duration":"7 days","difficulty":"hard"}]},
  {"phase":3,"title":"Defensive","tasks":[{"id":"cs6","title":"SIEM","description":"Log analysis","skill":"SIEM","priority":"high","duration":"7 days","difficulty":"hard"},{"id":"cs7","title":"Incident Response","description":"Handling breaches","skill":"IR","priority":"medium","duration":"5 days","difficulty":"hard"}]},
  {"phase":4,"title":"Advanced","tasks":[{"id":"cs8","title":"Cryptography","description":"Applied crypto","skill":"Crypto","priority":"medium","duration":"7 days","difficulty":"hard"},{"id":"cs9","title":"Cloud Security","description":"Securing cloud","skill":"Cloud Security","priority":"medium","duration":"5 days","difficulty":"hard"}]}
]'),
('software_engineer', 'Software Engineer', 'Generalist software engineering path.', '[
  {"phase":1,"title":"Foundation","tasks":[{"id":"se1","title":"Programming","description":"Pick a language","skill":"Programming","priority":"high","duration":"10 days","difficulty":"medium"},{"id":"se2","title":"Data Structures","description":"Arrays, trees, graphs","skill":"DSA","priority":"high","duration":"10 days","difficulty":"medium"},{"id":"se3","title":"Algorithms","description":"Sorting, searching, DP","skill":"Algorithms","priority":"high","duration":"10 days","difficulty":"hard"}]},
  {"phase":2,"title":"Development","tasks":[{"id":"se4","title":"Web Development","description":"Full-stack basics","skill":"Web","priority":"high","duration":"15 days","difficulty":"medium"},{"id":"se5","title":"Databases","description":"SQL and NoSQL","skill":"Database","priority":"high","duration":"7 days","difficulty":"medium"},{"id":"se6","title":"Git","description":"Version control","skill":"Git","priority":"medium","duration":"3 days","difficulty":"easy"}]},
  {"phase":3,"title":"Engineering","tasks":[{"id":"se7","title":"System Design","description":"Scalability","skill":"System Design","priority":"high","duration":"10 days","difficulty":"hard"},{"id":"se8","title":"Testing","description":"Unit and integration","skill":"Testing","priority":"medium","duration":"5 days","difficulty":"medium"}]},
  {"phase":4,"title":"Interview Prep","tasks":[{"id":"se9","title":"DSA Practice","description":"LeetCode","skill":"DSA","priority":"high","duration":"20 days","difficulty":"hard"},{"id":"se10","title":"Projects","description":"Build portfolio","skill":"Projects","priority":"high","duration":"10 days","difficulty":"medium"}]}
]')
ON CONFLICT (career_key) DO UPDATE SET
  career_name = EXCLUDED.career_name,
  description = EXCLUDED.description,
  phases = EXCLUDED.phases;
